baseURL = "https://terryho618.github.io/ComSocSci22_Final"
title = "The Spotify Artist Network"
description = "Analyzing the lyrical mood of artists on Spotify"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Anders NÃ¸rskov", "Terry Ho"]
    notebook = "/explainer-notebook.html"
    data = "https://onedrive.live.com/?authkey=%21AOLljeio1XGAHII&id=1E26245DC2140BDB%21516411&cid=1E26245DC2140BDB"
    github = "https://github.com/terryho618/ComSocSci22_Final"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network Analysis"
        link = "/network-analysis"
    [[params.nav]]
        label = "Lyrics"
        link = "/lyrics-analysis"
    [[params.nav]]
        label = "Louvain Network"
        link = "/louvain-network"
    [[params.nav]]
        label = "Spotify Network"
        link = "/genre-network"
    [[params.nav]]
        label = "Sentiment Network"
        link = "/sentiment-network"
    [[params.nav]]
        label = "Word Clouds"
        link = "/word-clouds"